(add-to-list 'load-path "/usr/share/emacs/site-lisp/color-theme")

;; note, this will look horrible in anything other than a 256 color black or transparent black terminal window.
(defun color-theme-tavis-tty ()
  (interactive)
  (require 'color-theme)
  (color-theme-initialize)
  (color-theme-install
   '(
     ((background-mode . dark)
      (border-color . "black")
      (cursor-color . "red")
      (foreground-color . "white")
      (mouse-color . "grey"))
     (default ((t (nil))))
     (default ((t (:foreground "white"))))
     (bold ((t (:bold t))))
     ;(bold-italic ((t (:underline t :foreground "white"))))
     (highlight ((t (:background "blue" :foreground "yellow"))))
     (italic ((t (:underline t :background "red"))))
     (underline ((t (:underline t))))
     ;
     ;:box (:line-width 1 :color "black" :style released-button) :height 0.9 :family "Arial"))
     (minibuffer-prompt ((t (:foreground "yellow"))))
     ;(modeline ((t (:background "#080808" :foreground "white"))))
     (modeline ((t (:background "#000087" :foreground "#ffffaf"))))
     ;(modeline-inactive ((t (:background "#161616" :foreground "#5f5f5f"))))
     (modeline-inactive ((t (:background "#161616" :foreground "white"))))
     (modeline-mousable-minor-mode ((t (:background "black" :foreground "white"))))
     (modeline-mousable ((t (:background "black" :foreground "white"))))
     ;(scroll-bar ((t (:background "#121212"))))
     ;(tool-bar ((t (:background "#121212" ))))
     ;(fringe ((t (:background "#121212"))))
     (region ((t (:background "#0000af" ))))
     (secondary-selection ((t (:background "#0000ff"))))
     (show-paren-match-face ((t (:background "#0000af"))))
     (show-paren-mismatch-face ((t (:background "magenta" :foreground "white"))))
     (flymake-errline ((t (:background "#870000"))))
     (flymake-warnline ((t (:background "#444444"))))
     (lineker-warning-face ((t (:background "#870000"))))

     (hl-line ((t (:background "#1a1a1a"))))
     (vline ((t (:background "#121212"))))

     (isearch ((t (:inherit region))))
     (isearch-secondary ((t (:inherit secondary-selection))))
     (lazy-highlight ((t (:inherit secondary-selection))))
     (match ((t (:background "#0000ff"))))
     (font-lock-builtin-face ((t (nil :foreground "blue"))))
     (font-lock-comment-face ((t (:foreground "red"))))
     (font-lock-constant-face ((t (:foreground "magenta"))))
     (font-lock-function-name-face ((t (:bold t :foreground "yellow"))))
     (font-lock-keyword-face ((t (:bold t :foreground "cyan"))))
     (font-lock-pseudo-keyword-face ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "green"))))
     (font-lock-type-face ((t (:bold t :foreground "yellow"))))
     (font-lock-variable-name-face ((t (:foreground "cyan"))))
     (font-lock-warning-face ((t (:bold t :foreground "magenta"))))
     (custom-comment-face ((t (:foreground "red"))))
     (custom-comment-tag-face ((t (:foreground "red"))))
     (py-pseudo-keyword-face ((t (:foreground "magenta"))))
     (py-builtins-face ((t (:bold t :foreground "magenta"))))
     (ecb-tag-header-face ((t (:background "#0000ff"))))
     (speedbar-highlight-face ((t (:background "#0000ff"))))
     (whitespace-newline ((t (:background "#000087"))))
     (trailing-whitespace ((t (:background "#000087"))))
     (linum ((t (:foreground "yellow" :background "#000087"))))
     (show-ws-tab ((t (:background "#4e4e4e"))))
     (which-func ((t (:foreground "cyan"))))
     (info-xref ((t (:inherit link :foreground "purple"))))
     (org-hide ((t (:foreground "#3a3a3a"))))
     (org-link ((t (:underline t :foreground "#afafff"))))
     (org-todo ((t (:foreground "red"))))

     (org-agenda-clocking ((t (:background "#111111" :underline t))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey"))))
     (org-agenda-structure ((t (:foreground "yellow"))))
     (org-clock-overlay ((t (:background "#0000d7"))))
     (org-column ((t (:background "#303030"))))
     (org-column-title ((t (:background "#00005f" :underline t :weight bold))))
     (org-table ((t (:foreground "#005fff"))))

     (outline-2 ((t (:foreground "#5fffff"))))
     (outline-3 ((t (:foreground "#00afaf"))))
     (outline-4 ((t (:foreground "#0087ff"))))
     (outline-5 ((t (:foreground "#0087af"))))

     (ac-completion-face ((t (:foreground "red"))))
     (popup-isearch-match ((t (:foreground "red"))))
     (ac-selection-face ((t (:foreground "black" :background "cyan"))))

     (log-view-message ((t (:foreground "#0087af" :background "#1c1c1c"))))
     (diff-header ((t (:foreground "#0087af" :background "#1c1c1c"))))
     (diff-file-header ((t (:foreground "#0087af" :background "#121212"))))
     (diff-refine-change ((t (:background "#1c1c1c"))))
     (diff-added ((t (:foreground "green"))))
     (diff-removed ((t (:foreground "red"))))
     (ediff-even-diff-A ((t (:background "#1c1c1c"))))
     (ediff-even-diff-B ((t (:background "#1c1c1c"))))
     (ediff-even-diff-C ((t (:background "#1c1c1c"))))
     (ediff-odd-diff-A ((t (:background "#1c1c1c"))))
     (ediff-odd-diff-B ((t (:background "#1c1c1c"))))
     (ediff-odd-diff-C ((t (:background "#1c1c1c"))))
     (ediff-current-diff-A ((t (:background "#00005f"))))
     (ediff-current-diff-B ((t (:background "#00005f"))))
     (ediff-current-diff-C ((t (:background "#00005f"))))
     (ediff-fine-diff-A ((t (:background "#5f005f"))))
     (ediff-fine-diff-B ((t (:background "#0000d7"))))
     (ediff-fine-diff-C ((t (:background "#0000d7"))))
     (bookmarkp-local-file-without-region ((t (:foreground "white"))))
     ))
  (smex-update))


(add-hook 'after-make-frame-functions
          (lambda (frame)
            (set-variable 'color-theme-is-global nil)
            (select-frame frame)
            (if window-system
                ();(color-theme-vim-colors)
              (color-theme-tavis-tty))))
(add-hook 'after-init-hook (lambda ()
                             (unless window-system
                               (color-theme-tavis-tty))))
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(provide 'dss-colorthemes)
